import type { JobListing, AIAnalysis } from "../job-scraper-pro/types";

// ── CSV export ─────────────────────────────────────────────────────────────
export function exportCSV(
  jobs: JobListing[],
  jobTitle: string,
  country: string,
  city: string
) {
  const meta = [
    ["AI Global Job Scraper Pro — Export Report"],
    [`Job Title: ${jobTitle}`, `Country: ${country}`, `City: ${city}`, `Date: ${new Date().toLocaleString()}`],
    [`Total Listings: ${jobs.length}`],
    [],
  ];
  const headers = [
    "Job Title","Company","Location","Country",
    "Job Type","Experience Level","Salary","Tags","Posted Date",
  ];
  const rows = jobs.map((j) => [
    `"${j.title}"`, `"${j.company}"`, `"${j.location}"`, `"${j.country}"`,
    j.jobType, j.experienceLevel, `"${j.salary}"`,
    `"${j.tags.join(", ")}"`, `"${j.postedDate}"`,
  ]);

  const csv = [
    ...meta.map((r) => r.join(",")),
    headers.join(","),
    ...rows.map((r) => r.join(",")),
  ].join("\n");

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `jobs-${jobTitle.toLowerCase().replace(/\s+/g, "-")}-${country.toLowerCase().replace(/\s+/g, "-")}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── PDF export ─────────────────────────────────────────────────────────────
export async function exportPDF(
  jobs: JobListing[],
  analysis: AIAnalysis,
  jobTitle: string,
  country: string,
  city: string
) {
  const jspdfModule = await import("jspdf");
  const jsPDF = (jspdfModule as any).default || (jspdfModule as any).jsPDF || jspdfModule;
  const doc = new (jsPDF as any)({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210;
  let y = 0;

  const newPage = () => { doc.addPage(); y = 20; };
  const check = (need: number) => { if (y + need > 275) newPage(); };

  // ── Cover header ──
  doc.setFillColor(10, 8, 25);
  doc.rect(0, 0, W, 46, "F");

  doc.setTextColor(160, 130, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("AI GLOBAL JOB SCRAPER PRO", 14, 12);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(17);
  doc.text(`${jobTitle} — Job Report`, 14, 24);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(140, 120, 210);
  doc.text(`Country: ${country}   |   City: ${city}   |   ${jobs.length} Listings`, 14, 34);
  doc.text(`Generated by AI Global Job Scraper Pro   |   ${new Date().toLocaleDateString()}`, 14, 41);
  y = 56;

  // ── AI Analysis section ──
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(130, 80, 240);
  doc.text("AI Career Analysis", 14, y); y += 8;

  // Stats
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(200, 180, 255);
  doc.text(`Market Demand:`, 14, y);
  doc.setTextColor(
    analysis.marketDemand === "High" ? 50 : analysis.marketDemand === "Medium" ? 230 : 220,
    analysis.marketDemand === "High" ? 200 : analysis.marketDemand === "Medium" ? 170 : 70,
    analysis.marketDemand === "High" ? 120 : 60,
  );
  doc.text(analysis.marketDemand, 55, y);
  doc.setTextColor(200, 180, 255);
  doc.text(`  |  Competition:`, 72, y);
  doc.setTextColor(
    analysis.competitionLevel === "Low" ? 50 : analysis.competitionLevel === "Medium" ? 230 : 220,
    analysis.competitionLevel === "Low" ? 200 : analysis.competitionLevel === "Medium" ? 170 : 70,
    analysis.competitionLevel === "Low" ? 120 : 60,
  );
  doc.text(analysis.competitionLevel, 116, y);
  doc.setTextColor(200, 180, 255);
  doc.text(`  |  Avg Salary:`, 134, y);
  doc.setTextColor(50, 200, 120);
  doc.text(analysis.avgSalary, 163, y);
  y += 8;

  // Skills
  doc.setFont("helvetica", "bold");
  doc.setTextColor(200, 180, 255);
  doc.text("Top Skills:", 14, y); y += 6;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180, 175, 210);
  const skillsLine = doc.splitTextToSize(analysis.topSkills.join("  •  "), W - 28);
  skillsLine.forEach((l: string) => { check(6); doc.text(l, 14, y); y += 6; });

  // Roadmap
  y += 3; check(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(200, 180, 255);
  doc.text("Learning Roadmap:", 14, y); y += 6;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180, 175, 210);
  analysis.careerRoadmap.forEach((step, i) => {
    check(7);
    doc.text(`${i + 1}.  ${step}`, 16, y); y += 7;
  });

  // Country insight
  y += 3; check(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(200, 180, 255);
  doc.text(`Country Insight — ${country}:`, 14, y); y += 6;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180, 175, 210);
  const insightLines = doc.splitTextToSize(analysis.countryInsight, W - 28);
  insightLines.forEach((l: string) => { check(7); doc.text(l, 14, y); y += 7; });

  // ── Job listings ──
  y += 8; check(16);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(130, 80, 240);
  doc.text("Job Listings", 14, y); y += 8;

  jobs.forEach((job, i) => {
    check(36);
    doc.setFillColor(18, 14, 38);
    doc.roundedRect(12, y, W - 24, 32, 2, 2, "F");
    doc.setDrawColor(70, 45, 140);
    doc.roundedRect(12, y, W - 24, 32, 2, 2, "S");

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(235, 228, 255);
    doc.text(`${i + 1}. ${job.title}`, 17, y + 7);

    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(160, 140, 210);
    doc.text(`${job.company}   •   ${job.location}   •   ${job.jobType}   •   ${job.experienceLevel}`, 17, y + 14);

    doc.setTextColor(60, 200, 130);
    doc.text(`Salary: ${job.salary}`, 17, y + 20);

    doc.setTextColor(100, 95, 130);
    doc.text(`Posted: ${job.postedDate}   |   Tags: ${job.tags.join(", ")}`, 17, y + 26);
    y += 38;
  });

  // Footer
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    doc.setFontSize(7.5);
    doc.setTextColor(70, 55, 110);
    doc.text("AI Global Job Scraper Pro — Portfolio Tool", 14, 290);
    doc.text(`Page ${p} of ${total}`, W - 28, 290);
  }

  doc.save(`job-report-${jobTitle.toLowerCase().replace(/\s+/g, "-")}-${country.toLowerCase().replace(/\s+/g, "-")}.pdf`);
}
